### ISSUE TITLE
New Geant4 version 10.2p02

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#10]
A new Geant4 patch is available 10.2p02. It is needed to create a new branch in cms-externals/geant4.

The Geant4 distribution page: http://cern.ch/geant4/support/download.shtml

**Comment by civanch** [comment]
@smuzaffar , @degano , @iahmad-khan , I make an issue instead of PR because likely have no permission to create new branches. The new branch likely should have a name "cms/4.10.02.p02"

**Comment by civanch** [comment]
@smuzaffar , @degano , @iahmad-khan , @davidlange6, how we can progress with this request?

**Comment by ghost** [comment]
@iahmad-khan ping!

**Comment by iahmad-khan** [comment]
@civanch the version updates  for data files, from the source page are as follows:

Versions updates for data files:
**gcc530next**                ->                        **gcc530**          ->                                 **current source**
eant4-G4NDL 4.4              ->              geant4-G4NDL 4.4        ->                       G4NDL4.5
geant4-G4EMLOW 6.35            ->     geant4-G4EMLOW 6.35    ->                  G4EMLOW6.48
geant4-G4PhotonEvaporation 3.0   -> geant4-G4PhotonEvaporation 3.0  -> G4PhotonEvaporation3.2
geant4-G4RadioactiveDecay 4.0    -> geant4-G4RadioactiveDecay 4.0     ->  G4RadioactiveDecay4.3.2
geant4-G4ENSDFSTATE 1.2.2     ->                     xxxxxxxxxxx                   ->  G4ENSDFSTATE1.2.3

Do we need update these files as well for new patch?

**Comment by civanch** [comment]
@iahmad-khan , you are right! This is the time when we should update data as well. May be we should be careful with G4NDL4.5 which is not used by CMS in production but may be larger than G4NDL4.4. Also may be these data already exit within list of externals but old one are linked to the DEVEL branch.

**Comment by iahmad-khan** [comment]
@civanch in gcc530 branch it is the same. table updated for gcc530. Can you figure out , what out of these files ,  we need to update , so that i can do it accordingly. thanks.

**Comment by civanch** [comment]
@iahmad-khan , for consistency we need update all files as you have identified.
