### ISSUE TITLE
identical CMakeLists.txt files in 4.10.04.b01

### ISSUE THREAD

**Issue by smuzaffar** [cms-externals/geant4#22]
@civanch , looks like we have a wrong cmake file source/CMakeLists.txt. It used to look like this
https://github.com/cms-externals/geant4/blob/cms/4.10.02.p02/source/CMakeLists.txt but now we have two idential file

https://github.com/cms-externals/geant4/blob/cms/4.10.04.b01/source/CMakeLists.txt 
https://github.com/cms-externals/geant4/blob/cms/4.10.04.b01/CMakeLists.txt

copying https://github.com/cms-externals/geant4/blob/cms/4.10.02.p02/source/CMakeLists.txt to 4.10.04.b01/source/CMakeLists.txt  let me start the build. Please check with geant4 developers why these files are identical.

**Comment by civanch** [comment]
@smuzaffar , in geant4 these files are different, likely something happens with the patch.
In the area where the patch was prepared both in ref07 and previous these files are identical, while if one clone a fresh variant geant4 from previous git branches they are different. Likely, it is my mistake but not clear how it is possible to do technically. If such happens we cannot trust to this patch/PR.

In a mean time a new reference version is available and a fresh tar is prepared:
~civanch/public/geant4.10.3ref08.tar.gz 
May be optimal make it as a new branch? We may skip ref07 now.

**Comment by smuzaffar** [comment]
thanks, I have now pushed the ref-08 change for https://github.com/cms-externals/geant4/tree/cms/4.10.04.b01
