### ISSUE TITLE
Switch DEVEL branch to Geant4 10.3p02

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#23]
Geant4 10.3p02 includes several technical fixes important for MT run with many threads. This patch is available at https://github.com/Geant4/geant4/releases 

No change of Geant4 data files is needed. This Geant4 version should be added only to the DEVEL branch.

**Comment by smuzaffar** [comment]
assign externals

**Comment by mrodozov** [comment]
@civanch the new geant4 version is now available here https://github.com/cms-externals/geant4/tree/cms/4.10.03.p02 and the tests could be followed here https://github.com/cms-sw/cmsdist/pull/3439

**Comment by smuzaffar** [comment]
thanks @mrodozov
