### ISSUE TITLE
Switch ROOT6 branch to the new reference version of Geant4 10.3ref09

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#24]
A new reference version of Geant4 is available 10.3ref09: ~vnivanch/public/geant4-10-03-ref-09.tar.gz

This version may be directly installed into 10.4beta branch and is needed for ROOT6 IB only. No new data files are provided, only source code.

**Comment by mrodozov** [comment]
@civanch , the new version is available in the https://github.com/cms-externals/geant4/commits/cms/4.10.04.b01 branch and the test could be followed here https://github.com/cms-sw/cmsdist/pull/3471

**Comment by civanch** [comment]
@mrodozov , thanks!
