### ISSUE TITLE
Create a branch for Geant4 10.4

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#27]
A new version of Geant4 is available. Because it is a new reference version which may be used for 2018 a new branch for it would be needed. It will be first used in 10_0_ROOT6 IB for testing.

The code is available: ~vnivanch/public/geant4-10-04/geant4.10.4.tar.gz
or
~vnivanch/public/geant4-10-04/geant4

It is needed to take the source from this place and not from Geant4 official git repository, because 3 bug fixes are added on top.

**Comment by smuzaffar** [comment]
@mrodozov , can you please take care of it

**Comment by mrodozov** [comment]
The new branch is here https://github.com/cms-externals/geant4/tree/cms/4.10.04
I'm testing it locally and then it will go on cmsdist as PR.
M.

**Comment by mrodozov** [comment]
I'm closing this
