### ISSUE TITLE
Switch GEANT4 branch to Geant4 10.5

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#36]
A new Geant4 10.5 is available ; https://github.com/Geant4/geant4/releases 

This new version requires new data files:
G4NDL4.5          - old dataset
G4EMLOW7.7
G4PhotonEvaporation5.3,
G4RadioactiveDecay5.3
G4SAIDDATA2.0
G4PARTICLEXS1.1  - new external
G4ABLA3.1,    - old dataset
G4INCL1.0
G4ENSDFSTATE2.2 - old dataset

Data are available at   http://geant4.web.cern.ch/support/download

**Comment by smuzaffar** [comment]
@civanch , there already a cmsdist Pr https://github.com/cms-sw/cmsdist/pull/4577/files to update geant4. Ok I see we are missing new data G4PARTICLEXS 1.1. what about two other data sets
- G4NEUTRONXS 2.0
- G4RealSurface 2.1.1
should we keep them in the distribution or they are not needed any more?

**Comment by civanch** [comment]
@smuzaffar , G4NEUTRONXS2.0 is needed for previous Geant4, since 10.5 it will not be used. G4RealSurface is needed for optical photon simulations and was never used by CMSSW. The dataset is small, it is up to you to include it now or not. It may be, that it will be never used.

**Comment by civanch** [comment]
done long ago
