### ISSUE TITLE
Switch Geant4 branch to Geant4 10.6beta

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#39]
A new Geant4 public version is available : https://github.com/Geant4/geant4/releases 
We need to use this new version in GEANT4 special IB for early testing.

This beta-release require modifications in other external packages:
New dataset G4PARTICLEXS2.0: http://geant4.web.cern.ch/support/download_beta 
New CLHEP version 2.4.1.2: http://proj-clhep.web.cern.ch/proj-clhep/clhep23.html
New VecGeom: https://gitlab.cern.ch/VecGeom/VecGeom/tree/v1.1.2

**Comment by mrodozov** [comment]
@civanch the IB is building and will be available later today, I'm closing this as resolved
