### ISSUE TITLE
Switch GEANT4 branch to the new reference version Geant4 10.6cand00

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#41]
A new Geant4 reference version is available : ~vnivanch/public/geant4-10-06-cand-00/geant4 or
https://cernbox.cern.ch/index.php/s/Tn5QBVWxnY3hwEc 

This Geant4 version is nearly 10.6 release, which is scheduled for December,6.
We need to use this new version in GEANT4 special IB for early testing in order to feedback.

This release require modifications in other external datasets:
G4EMLOW7.9 : https://cernbox.cern.ch/index.php/s/sRJD69a7wNwR51Y 
RadioactiveDecay5.4 : https://cernbox.cern.ch/index.php/s/p6O7bR0yYbNtIzv
PhotonEvaporation5.4 : https://cernbox.cern.ch/index.php/s/9XIxLDyJre3EyiJ
G4NDL4.6 : https://cernbox.cern.ch/index.php/s/5E8480vJsfvnQyg

**Comment by civanch** [comment]
@smuzaffar , @bsunanda, please have a look.

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
+externals
A new branch cms/4.10.06cand00 has been created using ~vnivanch/public/geant4-10-06-cand-00/geant4 . PR https://github.com/cms-sw/cmsdist/pull/5344 includes these changes.

**Comment by bsunanda** [comment]
I believe one need to use VecGeom version 1.1.4 rather than 0.5.0 which we have been using in the standard builds.
________________________________

**Comment by smuzaffar** [comment]
@bsunanda , GEANT4 IBs are already using VecGeom v1.1.4

**Comment by bsunanda** [comment]
That is great. Can you let me know the name of the build?
________________________________
