### ISSUE TITLE
Switch GEANT4 branch to Geant4 10.6

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#42]
A new Geant4 reference version is available : ~vnivanch/public/geant4-10-06/geant4 

We need to use this new version in GEANT4 special IB.

This release require modifications in other external datasets:
PhotonEvaporation5.5 : ~vnivanch/public/PhotonEvaporation5.5
CLHEP version 2.4.1.3: https://gitlab.cern.ch/CLHEP/CLHEP/tree/CLHEP_2_4_1_3 
VecGeom v1.1.5: https://gitlab.cern.ch/VecGeom/VecGeom/tree/v1.1.5

**Comment by smuzaffar** [comment]
@civanch , I can not access your ~vnivanch/public/geant4-10-06/geant4 . Can we just get it from https://github.com/Geant4/geant4/releases or do you have any changes on top of it in your area?

**Comment by civanch** [comment]
@smuzaffar , unfortunately, there are to fixes (pure numerical for rare division by zero and precision lost) on top of the release. For some reason all cmake and gmake related files have strong permissions in this directory. 
I will redo preparation  from scratch and let you know when ready.

**Comment by smuzaffar** [comment]
I think it is better to create a new branch using official geant4 sources and then we can apply the patches via PR

**Comment by smuzaffar** [comment]
@civanch , https://github.com/cms-externals/geant4/tree/cms/v10.6.0 is based on official geant4 tag https://github.com/Geant4/geant4/tree/v10.6.0 . Can you make a PR with additional changes? Or if yor provide me a tar.gz then I can do a diff and apply changes myself

**Comment by fabiocos** [comment]
I agree it is better to have a clean start, and track whatever addition on top of that in a transparent way

**Comment by civanch** [comment]
@smuzaffar , yes, I agree with this, indeed this would be more transparent.

**Comment by smuzaffar** [comment]
@civanch , do you have your updates? As a wrote, just provide me a tar with and I can make a PR

**Comment by civanch** [comment]
@smuzaffar , thanks, I will try making PR, simply missed that the branch is already there.

**Comment by smuzaffar** [comment]
this has been integrated in geant4 external repo now. once cms-sw/cmssw#28637 is merged then we can move forward with geant4 10.6 integration in CMSSW GEANT4 IBs.
