### ISSUE TITLE
Update GEANT4 IB with Geant4 10.6 patch01

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#44]
The first patch to Geant4 10.6 is available: https://github.com/Geant4/geant4/releases 

It requires  updated data files G4LEDATA, which can be taken from

~vnivanch/public/G4EMLOW7.9.1

This Geant4 version is expected to be merged to the master when validated. For the time being, it needs to be added to GEANT4 IB only.

**Comment by smuzaffar** [comment]
geant4 10.6.1 is now here https://github.com/cms-externals/geant4/tree/cms/v10.6.1 . CMs fix https://github.com/cms-externals/geant4/pull/43 ( https://github.com/cms-externals/geant4/pull/43 ) has already been merged upstream. So we do not have to patch it any more.

We will update cmsdist to integrate it in GEANT4 IBs.

**Comment by smuzaffar** [comment]
cmsdist PR to integrate 10.6.1 is https://github.com/cms-sw/cmsdist/pull/5562
