### ISSUE TITLE
Migrate GEANT4 branch to the updated version of VecGeom 1.1.6

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#45]
Updated version of VecGeom v1.1.6: https://gitlab.cern.ch/VecGeom/VecGeom/tree/v1.1.6 
includes important fix of G4CutTube used in PIxel and other fixes.

This version should be used in GEANT4 branch and also included into special build to test Geant4 10.6p01.

**Comment by smuzaffar** [comment]
@civanch , new version of vecgeom is now integrated. New IB of GEANT4 should have it
