### ISSUE TITLE
New Geant4 release 10.7beta for the GEANT branch

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#47]
New Geant4 release 10.7beta is available. It includes ongoing Geant4 developments toward 10.7 version to be released in December.  It may  be uploaded from url:

https://github.com/Geant4/geant4/releases

It is expected to use this only in GEANT4 branch. It is also needed to update VecGeom package with v1.1.7: https://gitlab.cern.ch/VecGeom/VecGeom/tree/v1.1.7

VecGeom modifications are in cmake, without these modifications VecGeom will not compile with Geant4 10.7beta.

**Comment by smuzaffar** [comment]
@mrodozov , can you please take care of it?

**Comment by smuzaffar** [comment]
this has been integrated for GEANT4 Ibs
