### ISSUE TITLE
Switch GEANT4 branch to Geant4 10.6ref09

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#48]
A new Geant4 reference version is available : ~vnivanch/public/geant4-10-06-ref-09
This Geant4 version includes main development for 2020.
We need to use this new version in GEANT4 special IB for early testing.

**Comment by mrodozov** [comment]
is this change to be put on the 10_6 branch:
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/g4_106/geant4.spec
or on the branch that is currently using geant4 10.7 and vecgeom 1.1.7 ? 
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/geant4/geant4.spec

**Comment by civanch** [comment]
@mrodozov , only on the branch with geant4 10.7 and vecgeom 1.1.7.
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/geant4/geant4.spec

**Comment by mrodozov** [comment]
So this is 10.7 release then, and I should better put it's name 10.7.something , or I keep the branch name 10.6.9 ?

**Comment by civanch** [comment]
10.6.9 is more precise - this is used by the G4 team.

**Comment by mrodozov** [comment]
Understood. It's clear now. Thank you
