### ISSUE TITLE
Switch to Geant4 10.7p02

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#53]
The Geant4 team provide a new patch 10.7p02:  https://geant4.web.cern.ch/support/download 

This patch includes mainly technical fixes, so it is possible first check on regression the master. If the regression will be broken, then this version should go some testing to GEANT4 and G4VECGEOM branches first.

**Comment by mrodozov** [comment]
@civanch you want me to try it against cmsdist/master, if it works we get it as it is, if it doesn't we first put it in 

https://github.com/cms-sw/cmsdist/tree/IB/CMSSW_12_0_X/geant4
https://github.com/cms-sw/cmsdist/tree/IB/CMSSW_12_0_X/geant4_vecgeom

to be fixed and then to cmsdist/master when it's fixed. Did I got it correct ?

**Comment by civanch** [comment]
@mrodozov , if we see no regression when compare with the master, this will not means that this patch is wrong or buggy, it simply will require more complicate statistics test. We should start from geant4 and geant4_vecgeom IBs and after will ask a validation campaign.

**Comment by mrodozov** [comment]
there is no difference between 
https://github.com/cms-sw/cmsdist/tree/IB/CMSSW_12_0_X/geant4_vecgeom
and 
https://github.com/cms-sw/cmsdist/tree/IB/CMSSW_12_0_X/master
for geant4 and vecgeom.
we stopped building geant4_vecgeom because of this (maybe? don't remember)
we can get the new tag on the geant4_vecgeom branch (and the non_vecgeom branch) and start building it again

**Comment by civanch** [comment]
@mrodozov , yes, the master and geant4_vecgeom are identical for some time since we updated master to the previous Geant4 tag. I agree, that 10.7p02 should be built in this branch. If last time this was built long ago we may not expect regression but we should not worry about too much.

**Comment by civanch** [comment]
#7041 and #7042 are merged
