### ISSUE TITLE
Switch G4VECGEOM to Geant4 10.7ref09

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#55]
Now Geant4 team is working on the new release 11.0. In order to be better prepared would it be possible to try to include Geant4 reference version and make a new G4VECGEOM IB ?

Geant4 10.7ref09 can be taken from: /afs/cern.ch/user/v/vnivanch/public/geant4.11.0/Geant4.10.7.9.tar.gz

There is a difficulty connected with DD4Hep, which also depend on Geant4 and it is not known if the current DD4Hep will compile on top of this version of Geant4 or not. CMSSW is already modified to be compatible with old and new Geant while DD4Hep not yet.

**Comment by smuzaffar** [comment]
@ddaina , can you please take care of this?

**Comment by ddaina** [comment]
FYI: https://github.com/cms-sw/cmsdist/pull/7436

**Comment by civanch** [comment]
+1
