### ISSUE TITLE
Switch G4VECGEOM and GEANT4 branches to Geant4 11.0

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#56]
We need to migrate Geant4 branches to the new Geant4 version 11.0.0 :
https://github.com/Geant4/geant4/releases 

This version required update of the data files: https://geant4.web.cern.ch/support/download 
G4EMLOW8.0 and G4PARTICLEXS4.0

**Comment by smuzaffar** [comment]
@iarspider , can you please take care of it?

**Comment by smuzaffar** [comment]
cmsdist branches where this should be updated are
- IB/CMSSW_12_3_X/geant4
- IB/CMSSW_12_3_X/geant4_vecgeom

**Comment by smuzaffar** [comment]
@iarspider FYI

**Comment by iarspider** [comment]
@smuzaffar on it.

**Comment by smuzaffar** [comment]
thanks @iarspider 
@civanch  @bsunanda , today we have first 12.3.X (GEANT4 and G4VECGEOM) IBs with geant4 11.0.0 available

**Comment by civanch** [comment]
Thanks!
