### ISSUE TITLE
Migration Geant4 branch G4VECGEOM to Geant4 11.1.ref04

### ISSUE THREAD

**Issue by civanch** [cms-externals/geant4#71]
Geant4 11.1.ref04 reference version is available. Please update G4VECGEOM branch. We need this to control Geant4 developments and to validate modifications for the next public patch to Geant4.

Code is available via:
http://vnivanch.web.cern.ch/vnivanch/hadronic/g4.11.1.ref04.tag.gz

**Comment by smuzaffar** [comment]
@civanch , I opened https://github.com/cms-sw/cmsdist/pull/8486 . Note that this is only for G4Vecgeom IBs. Do we need this to go in Geant4 IBs too?

**Comment by civanch** [comment]
@smuzaffar , thanks, let us see how G4VECGEOM will work and after decide about GEANT4.

**Comment by smuzaffar** [comment]
done, next G4VEcgeom IBs will be based on Geant4 11.1.ref04
